### ISSUE TITLE
Submit plugin to npm for discoverability

### ISSUE THREAD

**Issue by macdonst** [Macadamian/Cordova-BlinkUpPlugin#22]
It would be great if this was available on NPM.

https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

**Comment by dlanthier-mac** [comment]
It's a great idea, and it is part of the plan, and will occur very soon.

Dan

**Comment by dlanthier-mac** [comment]
Done. https://www.npmjs.com/package/cordova-blinkup-plugin
